#define PARMCHEAT	"spispopd"
#define STR_VERSION	"1.03"

#define STR_LOADING	"Loading"
#define STR_SAVING	"Saving"

#define STR_LGC		"Load Game called\n\""
#define STR_EMPTY	"empty"

#define	STR_THINK	"Thinking"

#define STR_SIZE1	"Use arrows to size"
#define STR_SIZE2	"ENTER to accept"
#define STR_SIZE3	"ESC to cancel"

#define STR_NOSPACE1	"There is not enough space"
#define STR_NOSPACE2	"on your disk to Save Game!"

#define STR_SAVECHT1	"Your Save Game file is,"
#define STR_SAVECHT2	"shall we say, \"corrupted\"."
#define STR_SAVECHT3	"But I'll let you go on and"
#define STR_SAVECHT4	"play anyway...."